GDB: Fix detection of ELF support when compiling with -Werror
Since commit 1ff6de031241c59d0ff9fa01d3c0a4049b0e97c9, bfd.h depends
on strncmp being present, so configuring with -Werror results in
the check for ELF support in BFD failing:
.../gdb/gdb/../bfd/elf-bfd.h: In function 'bfd_section_is_ctf':
.../gdb/gdb/../bfd/elf-bfd.h:3086:10: error: implicit declaration of function 'strncmp' [-Werror=implicit-function-declaration]
   return strncmp (name, ".ctf", 4) == 0 && (name[4] == 0 || name[4] == '.');